services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment_app
    container_name: django_app
    command: /gunicorn.sh
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    image: payment_app
    container_name: celery_worker
    command: celery -A payment worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env

  beat:
    image: payment_app
    container_name: celery_beat
    command: celery -A payment beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  static_volume:
